### ISSUE TITLE
Informative Test 6.3.6

### ISSUE THREAD

**Issue by MarcoKorinth** [secvisogram/csaf-validator-lib#169]
Test 6.3.6 is currently failing. 
Trying out older releases doesn't change this, even though the test worked at the time of releasing.
>6.3.6 valid
   informative/oasis_csaf_tc-csaf_2_0-2021-6-3-06-11.json

I think it is a problem with the "https://csaf.io" domain referenced in the test files. Changing this url makes all tests pass.

But I can't figure out why csaf.io domain is failing the test now, please have a look for yourself @tschmidtb51, maybe you can figure out what is going on here.

**Comment by tschmidtb51** [comment]
It looks like `testURL` results in the error as the site returns a HTTP status code 400. This is (most likely) due to an issue with the user-agent. Setting a specific string for the user-agent should resolve the issue. I would suggest we use something like `<package-name>/<version>`. Happy to hear your thoughts on that.

**Comment by MarcoKorinth** [comment]
Looks like you're right, setting an user-agent resolves the issue.
`<package-name>/<version>` as user-agent seems like a nice idea and shouldn't have any downsides as long as the csaf.io domain never blocks non-browser like user agents, which seems unlikely to ever be the case.
